// Generated by CoffeeScript 1.10.0
(function() {
  var entities, k, reversedEscapeChars, v;

  entities = {
    amp: '&',
    lt: '<',
    gt: '>',
    quot: '"',
    apos: "'"
  };

  reversedEscapeChars = {};

  for (let k in entities) {
    let v = entities[k];
    reversedEscapeChars[v] = k;
  }

  module.exports = {
    stripTags: function(s) {
      // return s.replace(/<\/?[^<>]*>/gi, '');
      return s.replace(/<[^>]*>/g, '');
    },
    escapeHTML: function(s) {
      return s.replace(/[&<>"']/g, function(m) {
        return "&" + reversedEscapeChars[m] + ";";
      });
    },
    decodeHTMLEntities: function(s) {
      return s.replace(/&#(\d+);?/g, function(_, code) {
        return String.fromCharCode(code);
      }).replace(/&#[xX]([A-Fa-f0-9]+);?/g, function(_, hex) {
        return String.fromCharCode(parseInt(hex, 16));
      }).replace(/&([^;\W]+;?)/g, function(m, e) {
        var target;
        switch (typeof (target = entities[e.replace(/;$/, '')])) {
          case 'number':
            return String.fromCharCode(target);
          case 'string':
            return target;
          default:
            return m;
        }
      });
    }
  };

}).call(this);
